import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import Hero from '@/components/hero'
import Choose_us from '@/components/choose_us/Choose_us'
import Services from '@/components/services'
import Reveal from '@/reveal'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Reveal>
          <Hero />
        </Reveal>
        <Reveal>
          <Choose_us />
        </Reveal>
        <Reveal>
          <Services />
        </Reveal>
      </main>
    </>
  )
}
